// export let sites = [
//   "stackoverflow",
//   "english.stackexchange",
//   "physics.stackexchange",
//   "movies.stackexchange",
//   "astronomy.stackexchange",
//   "raspberrypi.stackexchange",
//   "worldbuilding.stackexchange",
//   "askubuntu",
//   "superuser",
//   "math.stackexchange",
//   "unix.stackexchange",
//   "cstheory.stackexchange",
//   "codereview.stackexchange",
//   "security.stackexchange",
//   "softwareengineering.stackexchange",
//   "android.stackexchange",
//   "fitness.stackexchange",
//   "skeptics.stackexchange",
//   "scicomp.stackexchange",
//   "history.stackexchange",
//   "cs.stackexchange",
//   "hinduism.stackexchange",
//   "worldbuilding.stackexchange",
//   "networkengineering.stackexchange",
//   "ux.stackexchange",
// ];
export let sites = [
  "movies.stackexchange",
  "physics.stackexchange",
  "unix.stackexchange",
];
